### ISSUE TITLE
Orchestration comparison

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#42]
- [x] write blogpost and teaser

![Unikube COEC - Infographic (Inverted)HalfSize](https://user-images.githubusercontent.com/5262921/125797623-31d918aa-0355-467e-a5f1-57dc0213745f.png)

**Comment by Truthans** [comment]
I started:
https://docs.google.com/document/d/1wY_lLjCcPo21cjRtSWlDavfoU6w7yxqoawDKMDs3BvI/edit?usp=sharing

**Comment by Truthans** [comment]
@Schille can you post the updated infographic here?

**Comment by Truthans** [comment]
@Schille I am ready with a first rough draft. Could you take some time for an initial review?:
https://docs.google.com/document/d/1wY_lLjCcPo21cjRtSWlDavfoU6w7yxqoawDKMDs3BvI/edit?usp=sharing

**Comment by Schille** [comment]
Here the latest version
![Unikube COEC - Infographic (Inverted) (V3)](https://user-images.githubusercontent.com/676722/126765397-5b0f5079-4894-43ed-b2fa-d0616db18a31.png)

**Comment by Schille** [comment]
Nice text tho. I'd suggest to have @tschale take a look as well.

**Comment by Truthans** [comment]
@tschale I have reviewed the text once more after @Schille's comments. Could you have another look at this?

**Comment by tschale** [comment]
@Truthans Looks good! I've corrected few minor spelling stuff and left two minor comments in the document. And I'm not so sure about all those commas and possibly missing commas, but I have no knowledge on that part...

**Comment by marty-2015** [comment]
- [x] Proof Reading
- [ ] Teaser Social Media
- [ ] Blogpost live

**Comment by marty-2015** [comment]
@tschale please review this blogpost, still not sure about the first picture. 
https://unikube.io/blog/container-orchestration-cloud-or-on-site/

**Comment by marty-2015** [comment]
@Truthans what do you think about the image issue?

**Comment by Truthans** [comment]
> @Truthans what do you think about the image issue?

@marty-2015 what issue do you mean? That the graphic is pixelated/blurry? If yes, then this comes from the image being scaled up programmatically. It's something that we need to adress with Tobi.

**Comment by marty-2015** [comment]
> > @Truthans what do you think about the image issue?
> 
> @marty-2015 what issue do you mean? That the graphic is pixelated/blurry? If yes, then this comes from the image being scaled up programmatically. It's something that we need to adress with Tobi.

@Truthans the question is out of date ;)

**Comment by marty-2015** [comment]
@Schille please post on your page and in Linkedin DevOps group:

**Text:** 
☁️  Cloud or on-site? There are many ways to orchestrate your container landscape 🌳 , and I would like to give you a brief introduction to your options. Including a useful graph that shows all the pros 👍  and cons 👎
 
Check it out now:
👉  https://unikube.io/blog/container-orchestration-cloud-or-on-site/

#devops #containerization #kubernetes #cloudnative

**DevOps Group:** https://www.linkedin.com/groups/2825397/
**Image for Blogpost:** https://drive.google.com/file/d/1FtDAsrx6jI6nPtVjt4WZKiti28-KevPx/view?usp=sharing

**Publish:** from 29.09.

**Comment by Schille** [comment]
done
